### ISSUE TITLE
Doc: web part get started, should use BridgeStore

### ISSUE THREAD

**Issue by codecomeon** [gronxb/webview-bridge#31]
![image](https://github.com/gronxb/webview-bridge/assets/39626330/a743e062-a040-47d7-b770-87cfd11c7772)

Must to be `<BridgeStore<AppBridge>>`

**Comment by codecomeon** [comment]
And, `dts-bundle-generator` the latest version AppBridge file, will throw error~
![image](https://github.com/gronxb/webview-bridge/assets/39626330/d454b0d3-76fa-4df3-a8ca-5f35beee0717)

**Comment by gronxb** [comment]
Hello 😀.

If you've exported the AppBridge from the React Native part as shown below, it's okay to use linkBridge<AppBridge>(); in the web part because it wraps around the BridgeStore.
<img width="548" alt="image" src="https://github.com/gronxb/webview-bridge/assets/41789633/9a6ed517-da2f-4e78-afbd-1456cf2a9f9c">
In the photo above, AppBridge is compatible with BridgeStore.

```ts
export type AppBridge = typeof appBridge;
```

I believe the generic error in linkBridge occurred during the type creation process.

Having a simple repro could make it easier to solve this issue.

For now, here are some considerations:
First, please separate the code where type appBridge is declared, and only declare the part responsible for the bridge in the file as follows:

```ts
// This file is src/bridge.ts
import { bridge } from "@webview-bridge/react-native";
import InAppBrowser from "react-native-inappbrowser-reborn";

export const appBridge = bridge({
  async getMessage() {
    return "I'm from native" as const;
  },
  async openInAppBrowser(url: string) {
    if (await InAppBrowser.isAvailable()) {
      await InAppBrowser.open(url);
    }
  },
});
export type AppBridge = typeof appBridge;
```

Secondly, you need to check if the settings in tsconfig.build.json are correct.
Lastly, I'm curious about which command you entered, for example:
```sh
> pnpm dts-bundle-generator -o output.ts src/bridge.ts --project=tsconfig.build.json --no-check
```

**Comment by gronxb** [comment]
If you could create a simple repro when you have time, I can quickly check and provide assistance.

Currently, no errors have been found in the production environment I have.

**Comment by codecomeon** [comment]
Well done~thanks！
