### ISSUE TITLE
Query on Using React Hooks in registerWebMethod Implementation

### ISSUE THREAD

**Issue by nick0504k** [gronxb/webview-bridge#51]
Thank you very much for your hard work. I was wondering if it is possible to use React hooks in registerWebMethod.

**Comment by gronxb** [comment]
Hello,

When working with `webview-bridge`, it's important to consider the type system. Using `registerWebMethod` makes it difficult to share types between both repositories, and it's not very React-friendly.

Due to the lack of diverse use cases, I don't think calling web methods from native code is an ideal scenario. However, since others seem interested in this functionality, I'm considering how they can communicate effectively.

I haven't found a scenario where using web methods is necessary, but since it is in demand, I'm exploring different communication methods between native and web. My current idea is to avoid declaring types on both sides and instead declare types only on the native side. This way, when native accesses the web, it would use an event-based approach rather than a method-based approach.

Here's a draft of my idea:
GitHub Pull Request #35

There haven't been any direct requests so far, so I've postponed the development. However, if it's needed, I will add it as soon as possible.

**Also, I would appreciate it if you could share scenarios where using web methods would be necessary.**

Thank you for your feedback and suggestions.

**Comment by nick0504k** [comment]
Thank you for your prompt response! In my project, I aim to minimize the use of native components as much as possible, so even the alert dialog is implemented using React. In a try/catch block, I would like to display the alert dialog from React by utilizing either registerWebMethod or shared state.

**Comment by nick0504k** [comment]
Personally, I have found registerWebMethod to be useful for setting localStorage in the WebView.

**Comment by gronxb** [comment]
In version 1.5.0, the postMessage feature has been introduced. Check it out here: [Using a post message](https://gronxb.github.io/webview-bridge/using-a-post-message.html).

Handling localStorage registration through postMessage might also be more appropriate.

[Release](https://github.com/gronxb/webview-bridge/releases/tag/v1.5.0)
