### ISSUE TITLE
How to Manage Shared State Across Multiple and Dynamically Created WebViews?

### ISSUE THREAD

**Issue by aumgiri9393** [gronxb/webview-bridge#84]
Hi @gronxb,
I'm using the webview-bridge library in my React Native project, and I have encountered a scenario where I need some guidance on best practices.
**Problem:**
1. **Shared State Management:** I have multiple WebViews that need to access the same state using the bridge. However, the data being passed to each WebView instance is different. I want to maintain a shared state across WebViews for certain operations but ensure that the data sent to each WebView remains distinct. What's the best way to handle this scenario using the bridge?
2. **Dynamic WebView Creation:** I'm dynamically creating WebViews in my application, and each new WebView instance may need to access different data. However, I haven't added any functionality yet to handle dynamic WebViews properly. I'd appreciate some advice on how to manage state in dynamically created WebViews, particularly ensuring that each WebView is isolated with its own unique data while having access to shared state when needed.
3. **Data Isolation:** How do I ensure that each WebView has its own context or data isolation when using the same bridge? For example, if WebView A and WebView B need different chartData, how can I ensure both handle their data separately without one overriding the other's state?

We have decided to use a single bridge for all WebViews instead of multiple bridges. The reason for this is that we want to use a single static HTML file for all the WebViews in the app. This approach is being used to reduce the app's size since loading the HTML dynamically for each WebView could significantly increase the app size. By using one static HTML file, we can optimize the size of the app and keep the WebView interactions centralized.

**Expected Behavior:**
1. Each dynamically created WebView should be able to access a unique state or data.
2. The WebView state should remain consistent across WebViews.
3. Data should be updated dynamically without any mismatches or performance issues.

I have a minimal React Native app that uses two WebViews. The app does not currently handle dynamic WebViews or state sharing properly, and I need guidance on how to tackle this issue.
Here’s the link to the GitHub repository for the minimal app, which includes the WebView bridge implementation: https://github.com/aumgiri9393/webViewPOC/tree/rn-71
**Additional Information:**
The app is designed to display two static WebViews, but I want to expand it to handle dynamic WebViews.
Each WebView should receive unique data via the bridge, and I need to figure out how to handle state consistency across all WebViews.
I appreciate any advice or solutions you can offer!

**Comment by gronxb** [comment]
The shared state created by `const appBridge = bridge(...)` is classified as a global state within React Native. When `appBridge` is injected via `createWebView`, this shared state propagates to the WebView.

Since the global state from `bridge(...)` and `createWebView` are maintained in a single context, creating independent shared states would require two separate `bridge(...)` instances and two separate `createWebView()` instances.

Therefore, this is currently the intended behavior, and implementing it otherwise might be challenging.

====

However, it seems that what you want is:

```tsx
const appBridge = bridge({
  // shared state
});

const Bridge = createWebView({ bridge: appBridge });

<Bridge.WebView source={{
  uri: 'http://localhost:5173',
}} /> // same URL, same bridge, but different initial data

<Bridge.WebView source={{
  uri: 'http://localhost:5173',
}} /> // same URL, same bridge, but different initial data
```

In other words, you want isolated shared data within the WebView, even though they are created using a single bridge. Is that correct?

====

If this is what you’re aiming for, additional development may be needed.

For example, the solution might look something like this: (though this is not finalized)
```tsx
const appBridge = isolateBridge({
  // shared state
});

const Bridge = createWebView({
  bridge: appBridge,
});

<Bridge.WebView 
  source={{ uri: 'http://localhost:5173' }}
  isolatedKey="unique_string_1"  // unique isolated key
/> // same URL, same bridge, but different initial data

<Bridge.WebView 
  source={{ uri: 'http://localhost:5173' }}
  isolatedKey="unique_string_2" // unique isolated key
/> // same URL, same bridge, but different initial data

// React Native Side
const sharedText = useBridge(appBridge, (state) => state.sharedText, {
  isolatedKey: "unique_string_1"
});

const sharedText = useBridge(appBridge, (state) => state.sharedText, {
  isolatedKey: "unique_string_2"
});

// Web Side (no changes)
const sharedText = useBridge(bridge.store, (state) => state.sharedText)
```
This would allow for isolated data within the same WebView, differentiated by unique isolatedKey values.
